# Generated by Django 6.0.3 on 2026-05-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_quiz_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
