# Generated by Django 6.0.3 on 2026-03-30 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_quiz_questions_question_inquiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='owner',
        ),
        migrations.AddField(
            model_name='quiz',
            name='creator',
            field=models.ManyToManyField(to='core.creator'),
        ),
        migrations.AlterField(
            model_name='question',
            name='InQuiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.quiz'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answerRight',
            field=models.IntegerField(),
        ),
    ]
