# Generated by Django 6.0.3 on 2026-05-01 12:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_quiz_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='publicToken',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='publicTokenEnabled',
            field=models.BooleanField(default=True),
        ),
    ]
