# Generated by Django 6.0.3 on 2026-05-01 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_quiz_publictoken_quiz_publictokenenabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('results_viewer', 'Results viewer')], default='editor', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_roles', to='core.creator')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='core.quiz')),
            ],
            options={
                'unique_together': {('quiz', 'creator')},
            },
        ),
    ]
