# Generated by Django 6.0.3 on 2026-05-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_quizattempt_quizattemptanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='publicTokenEnabled',
            field=models.BooleanField(default=True, verbose_name='Public access'),
        ),
    ]
